/// Flutter icons BcxIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  BcxIcons
///      fonts:
///       - asset: fonts/BcxIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class BcxIcons {
  BcxIcons._();

  static const _kFontFam = 'BcxIcons';
  static const String _kFontPkg = null;

  static const IconData golfing = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
